package com.revscope.core.intelligence.dtc

/**
 * Plain-language explanation of a DTC code, optionally generated by Claude AI.
 *
 * @property code        DTC code string (e.g. "P0300")
 * @property explanation Human-readable description
 * @property source      Origin: an AiProvider.providerId ("anthropic" | "openai" | "gemini" |
 *                        "custom") on success, or "cache" | "fallback" | "no_key" | "offline"
 */
data class DtcExplanation(
    val code: String,
    val explanation: String,
    val source: String,
) {
    companion object {
        fun noApiKey(code: String) = DtcExplanation(
            code = code,
            explanation = "Para obtener explicaciones con IA, configura un proveedor en Ajustes → Inteligencia artificial.",
            source = "no_key",
        )

        fun offline(code: String) = DtcExplanation(
            code = code,
            explanation = "Código $code — sin conexión. Conectate a internet para obtener la explicación IA.",
            source = "offline",
        )

        fun fallback(code: String) = DtcExplanation(
            code = code,
            explanation = "Código $code — la explicación IA no está disponible en este momento.",
            source = "fallback",
        )
    }
}
